name: Test and Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Adjust to your PHP version
          extensions: mbstring, sqlite3
          tools: composer

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist

      - name: Generate App Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Set Up SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Migrate and Seed Database
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: database/database.mysql
        run: |
          php artisan migrate:fresh --seed

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust to your Node.js version

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run NPM Build
        run: npm run build

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: database/database.mysql
        run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: laravel-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/blog-ssh/htdocs/laravelblog.techland360.com
            php artisan down || true
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            git pull origin dev
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan clear-compiled
            php artisan optimize
            npm ci
            npm run build
            php artisan migrate --force
            php artisan up
